<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span><ul class="toc-item"><li><span><a href="#What-is-Machine-Learning?" data-toc-modified-id="What-is-Machine-Learning?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>What is Machine Learning?</a></span><ul class="toc-item"><li><span><a href="#Supervised-learning" data-toc-modified-id="Supervised-learning-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Supervised learning</a></span></li><li><span><a href="#Unsupervised-Learning" data-toc-modified-id="Unsupervised-Learning-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Unsupervised Learning</a></span></li></ul></li><li><span><a href="#ML-vs.-AI-vs.-Data-Science" data-toc-modified-id="ML-vs.-AI-vs.-Data-Science-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>ML vs. AI vs. Data Science</a></span></li><li><span><a href="#7-Steps-of-the-Machine-Learning-Process" data-toc-modified-id="7-Steps-of-the-Machine-Learning-Process-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>7 Steps of the Machine Learning Process</a></span></li></ul></li><li><span><a href="#Data-Manipulation-with-NumPy" data-toc-modified-id="Data-Manipulation-with-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Data Manipulation with NumPy</a></span><ul class="toc-item"><li><span><a href="#Arrays" data-toc-modified-id="Arrays-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Arrays</a></span></li><li><span><a href="#Basics" data-toc-modified-id="Basics-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Basics</a></span><ul class="toc-item"><li><span><a href="#arange" data-toc-modified-id="arange-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>arange</a></span></li><li><span><a href="#linspace" data-toc-modified-id="linspace-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>linspace</a></span></li><li><span><a href="#reshape" data-toc-modified-id="reshape-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>reshape</a></span></li><li><span><a href="#flatten" data-toc-modified-id="flatten-2.2.4"><span class="toc-item-num">2.2.4&nbsp;&nbsp;</span>flatten</a></span></li><li><span><a href="#Transposing" data-toc-modified-id="Transposing-2.2.5"><span class="toc-item-num">2.2.5&nbsp;&nbsp;</span>Transposing</a></span></li><li><span><a href="#Zeros-and-ones" data-toc-modified-id="Zeros-and-ones-2.2.6"><span class="toc-item-num">2.2.6&nbsp;&nbsp;</span>Zeros and ones</a></span></li></ul></li><li><span><a href="#Math" data-toc-modified-id="Math-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Math</a></span><ul class="toc-item"><li><span><a href="#Arithmetic" data-toc-modified-id="Arithmetic-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>Arithmetic</a></span></li><li><span><a href="#Non-linear-functions" data-toc-modified-id="Non-linear-functions-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>Non-linear functions</a></span></li><li><span><a href="#Matrix-multiplication" data-toc-modified-id="Matrix-multiplication-2.3.3"><span class="toc-item-num">2.3.3&nbsp;&nbsp;</span>Matrix multiplication</a></span></li></ul></li><li><span><a href="#Random" data-toc-modified-id="Random-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Random</a></span><ul class="toc-item"><li><span><a href="#Random-integers" data-toc-modified-id="Random-integers-2.4.1"><span class="toc-item-num">2.4.1&nbsp;&nbsp;</span>Random integers</a></span></li><li><span><a href="#Utility-functions" data-toc-modified-id="Utility-functions-2.4.2"><span class="toc-item-num">2.4.2&nbsp;&nbsp;</span>Utility functions</a></span></li><li><span><a href="#Distributions" data-toc-modified-id="Distributions-2.4.3"><span class="toc-item-num">2.4.3&nbsp;&nbsp;</span>Distributions</a></span></li><li><span><a href="#Custom-sampling" data-toc-modified-id="Custom-sampling-2.4.4"><span class="toc-item-num">2.4.4&nbsp;&nbsp;</span>Custom sampling</a></span></li></ul></li><li><span><a href="#Indexing" data-toc-modified-id="Indexing-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Indexing</a></span><ul class="toc-item"><li><span><a href="#Argmin-and-argmax" data-toc-modified-id="Argmin-and-argmax-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>Argmin and argmax</a></span></li></ul></li><li><span><a href="#Filtering" data-toc-modified-id="Filtering-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Filtering</a></span></li><li><span><a href="#Statistics" data-toc-modified-id="Statistics-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Statistics</a></span></li><li><span><a href="#Aggregation" data-toc-modified-id="Aggregation-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Aggregation</a></span></li><li><span><a href="#Saving-Data" data-toc-modified-id="Saving-Data-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>Saving Data</a></span></li></ul></li><li><span><a href="#Data-Analysis-with-pandas" data-toc-modified-id="Data-Analysis-with-pandas-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Analysis with pandas</a></span></li></ul></div>

# Introduction


## What is Machine Learning?

Machine learning is the branch of science that deals with algorithms and systems performing specific tasks using patterns and inference, rather than explicitly programmed instructions. There are a variety of different use cases for machine learning, from image recognition to text generation. Most machine learning tasks generalize to one of the following two learning types:

### Supervised learning

Using labeled data to train a model. The labels for the training dataset represent the class/category that each data observation belongs to. After training, the model should be able to predict labels for new data observations (from the same population distribution as the training data).

Example: Let’s say you’re training a machine learning model to predict whether a picture contains a lake or not. With supervised learning, you would train a model on a dataset of pictures where the label for each picture is “Yes” if it contains a lake or “No” if it doesn’t. After training, the model will be able to take in a picture and determine whether or not it contains a lake.


### Unsupervised Learning

Using unlabeled data to allow a model to learn relationships between data observations and pick up on underlying patterns. Most data in the world is unlabeled, which makes unsupervised learning a very useful method of machine learning.

Example: Going back to the same picture dataset from above, but now assume the training dataset is unlabeled. Using unsupervised learning, a model will be able to pick up on the inherent differences between pictures with a lake and pictures without a lake, e.g. differences in pixel color or orientation. This allows the model to cluster the pictures into two separate groups.
If it is possible to get large enough labeled training datasets, supervised learning is the way to go. However, it is often difficult to get fully labeled datasets, which is why many tasks require unsupervised learning or semi-supervised learning (a mix of supervised and unsupervised learning). Deciding which type of learning method to use is only the first step towards creating a machine learning model. You also need to choose the proper model architecture for your task and, most importantly, be able to process data into a training pipeline and interpret/analyze model results.

## ML vs. AI vs. Data Science

People often throw around the terms “machine learning”, “artificial intelligence”, and “data science” interchangeably. In reality, machine learning is a subset of artificial intelligence and overlaps heavily with data science. Artificial intelligence deals with any technique that allows machines to display “intelligence”, similar to humans. Machine learning is one of the main techniques used to create artificial intelligence, but other non-ML techniques (e.g. alpha-beta pruning, rule-based systems) are also widely used in AI.

On the other hand, data science deals with gathering insights from datasets. Traditionally, data scientists have used statistical methods for gathering these insights. However, as machine learning continues to grow, it has also penetrated into the field of data science.

In industry, any data scientist or AI researcher needs to have a good understanding of machine learning. Machine learning in industry has allowed us to create wonderful autonomous systems. These systems have matched, or sometimes even exceeded, the best human performance in their respective fields. A good example is AlphaGo, a machine-learning based system that has beaten the best human Go players in the world.

## 7 Steps of the Machine Learning Process

Data Collection: The process of extracting raw datasets for the machine learning task. This data can come from a variety of places, ranging from open-source online resources to paid crowdsourcing. The first step of the machine learning process is arguably the most important. If the data you collect is poor quality or irrelevant, then the model you train will be poor quality as well.

- Data Processing and Preparation: Once you’ve gathered the relevant data, you need to process it and make sure that it is in a usable format for training a machine learning model. This includes handling missing data, dealing with outliers, etc.

- Feature Engineering: Once you’ve collected and processed your dataset, you will likely need to transform some of the features (and sometimes even drop some features) in order to optimize how well a model can be trained on the data.

- Model Selection: Based on the dataset, you will choose which model architecture to use. This is one of the main tasks of industry engineers. Rather than attempting to come up with a completely novel model architecture, most tasks can be thoroughly performed with an existing architecture (or combination of model architectures).

- Model Training and Data Pipeline: After selecting the model architecture, you will create a data pipeline for training the model. This means creating a continuous stream of batched data observations to efficiently train the model. Since training can take a long time, you want your data pipeline to be as efficient as possible.

- Model Validation: After training the model for a sufficient amount of time, you will need to validate the model’s performance on a held-out portion of the overall dataset. This data needs to come from the same underlying distribution as the training dataset, but needs to be different data that the model has not seen before.

- Model Persistence: Finally, after training and validating the model’s performance, you need to be able to properly save the model weights and possibly push the model to production. This means setting up a process with which new users can easily use your pre-trained model to make predictions.



# Data Manipulation with NumPy


## Arrays


In [1]:
import numpy as np  # import the NumPy library

# Initializing a NumPy array
arr = np.array([-1, 2, 5], dtype=np.float32)

# Print the representation of the array
print(repr(arr))


array([-1.,  2.,  5.], dtype=float32)


In [3]:
arr = np.array([0, 1, 2])
print(arr.dtype)
print(arr)

arr = arr.astype(np.float32)
print(arr.dtype)
print(arr)



int64
[0 1 2]
float32
[0. 1. 2.]


In [4]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))
print(arr)

arr = np.array([np.nan, 'abc'])
print(repr(arr))
print(arr)

# Will result in a ValueError
np.array([np.nan, 1, 2], dtype=np.int32)


array([nan,  1.,  2.])
[nan  1.  2.]
array(['nan', 'abc'], dtype='<U32')
['nan' 'abc']


ValueError: cannot convert float NaN to integer

Infinity

To represent infinity in NumPy, we use the np.inf special value. We can also represent negative infinity with -np.inf.

The code below shows an example usage of np.inf. Note that np.inf cannot take on an integer type.


In [5]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))
print(arr)

arr = np.array([-np.inf, 1])
print(repr(arr))
print(arr)

# Will result in an OverflowError
np.array([np.inf, 3], dtype=np.int32)


True
array([inf,  5.])
[inf  5.]
array([-inf,   1.])
[-inf   1.]


OverflowError: cannot convert float infinity to integer

In [7]:
arr = np.array([np.nan, 2, 3, 4, 5])

arr2 = arr.copy()
arr2[0] = 10

print(arr[0])
print(arr2[0])


nan
10.0


In [9]:
loat_arr = np.array([1, 5.4, 3])
float_arr2 = arr2.astype(np.float32)

print(loat_arr)
print(float_arr2)


[1.  5.4 3. ]
[10.  2.  3.  4.  5.]


In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6]],
                  dtype=np.float32)

print(matrix)


[[1. 2. 3.]
 [4. 5. 6.]]


## Basics


### arange


In [12]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))



array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


### linspace


To specify the number of elements in the returned array, rather than the step size, we can use the np.linspace function.


In [13]:
arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))


array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


### reshape


In [14]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


### flatten


In [15]:
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


### Transposing


In [16]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


The function takes in a required first argument, which will be the array we want to transpose. It also has a single keyword argument called axes, which represents the new permutation of the dimensions.

The permutation is a tuple/list of integers, with the same length as the number of dimensions in the array. It tells us where to switch up the dimensions. For example, if the permutation had 3 at index 1, it means the old third dimension of the data becomes the new second dimension (since index 1 represents the second dimension).

The code below shows an example usage of the np.transpose function with the axes keyword argument. The shape property gives us the shape of an array.



In [18]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
print(arr)
transposed = np.transpose(arr, axes=(1, 2, 0))
print(transposed)

print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[ 0  8 16]
  [ 1  9 17]]

 [[ 2 10 18]
  [ 3 11 19]]

 [[ 4 12 20]
  [ 5 13 21]]

 [[ 6 14 22]
  [ 7 15 23]]]
arr shape: (3, 4, 2)
transposed shape: (4, 2, 3)


### Zeros and ones


In [19]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))



array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


If we want to create an array of 0's or 1's with the same shape as another array, we can use np.zeros_like and np.ones_like.

The code below shows example usages of np.zeros_like and np.ones_like.


In [20]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))


array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


In [21]:
arr = np.arange(12)
reshaped = np.reshape(arr, (2, 3, 2))

print(arr)
print(reshaped)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [22]:
flattened = reshaped.flatten()
transposed = np.transpose(reshaped, axes=(1, 2, 0))


print(flattened)
print(transposed)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 1  7]]

 [[ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]]]


In [23]:
zeros_arr = np.zeros(5)
ones_arr = np.ones_like(transposed)

print(zeros_arr)
print(ones_arr)


[0. 0. 0. 0. 0.]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [25]:
points = np.linspace(-3.5, 1.5, num=101)

print(points)


[-3.5  -3.45 -3.4  -3.35 -3.3  -3.25 -3.2  -3.15 -3.1  -3.05 -3.   -2.95
 -2.9  -2.85 -2.8  -2.75 -2.7  -2.65 -2.6  -2.55 -2.5  -2.45 -2.4  -2.35
 -2.3  -2.25 -2.2  -2.15 -2.1  -2.05 -2.   -1.95 -1.9  -1.85 -1.8  -1.75
 -1.7  -1.65 -1.6  -1.55 -1.5  -1.45 -1.4  -1.35 -1.3  -1.25 -1.2  -1.15
 -1.1  -1.05 -1.   -0.95 -0.9  -0.85 -0.8  -0.75 -0.7  -0.65 -0.6  -0.55
 -0.5  -0.45 -0.4  -0.35 -0.3  -0.25 -0.2  -0.15 -0.1  -0.05  0.    0.05
  0.1   0.15  0.2   0.25  0.3   0.35  0.4   0.45  0.5   0.55  0.6   0.65
  0.7   0.75  0.8   0.85  0.9   0.95  1.    1.05  1.1   1.15  1.2   1.25
  1.3   1.35  1.4   1.45  1.5 ]


## Math


### Arithmetic


In [26]:
arr = np.array([[1, 2], [3, 4]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))


array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [28]:
def f2c(temps):
    return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))


Celsius: array([  0., -20., -10., -40.])


### Non-linear functions

In [29]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))


array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [30]:
arr = np.array([[1, 2], [3, 4]])
# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))
arr2 = np.array([[10.2, 4], [3, 5]])
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))


array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


https://numpy.org/doc/stable/reference/routines.math.html


### Matrix multiplication


In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(np.matmul(arr3, arr4))
print(repr(np.matmul(arr4, arr3)))
print(np.matmul(arr4, arr3))
# This will result in ValueError
print(repr(np.matmul(arr3, arr3)))



27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
[[  5   4  -7]
 [  9   8 -13]
 [ 13  12 -19]]
array([[  4,   4],
       [-11, -10]])
[[  4   4]
 [-11 -10]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [33]:
arr = np.array([[-0.5, 0.8, -0.1], [0.0, -1.2, 1.3]])
arr2 = np.array([[1.2, 3.1], [1.2, 0.3], [1.5, 2.2]])

print(arr)
print(arr2)


[[-0.5  0.8 -0.1]
 [ 0.  -1.2  1.3]]
[[1.2 3.1]
 [1.2 0.3]
 [1.5 2.2]]


In [34]:
multiplied = arr * np.pi
added = arr + multiplied
squared = added**2

print(multiplied)
print(added)
print(squared)


[[-1.57079633  2.51327412 -0.31415927]
 [ 0.         -3.76991118  4.08407045]]
[[-2.07079633  3.31327412 -0.41415927]
 [ 0.         -4.96991118  5.38407045]]
[[ 4.28819743 10.97778541  0.1715279 ]
 [ 0.         24.70001718 28.98821461]]


In [36]:
exponential = np.exp(squared)
logged = np.log(arr2)

print(exponential)
print(logged)


[[7.28350596e+01 5.85587272e+04 1.18711726e+00]
 [1.00000000e+00 5.33434578e+10 3.88527393e+12]]
[[ 0.18232156  1.13140211]
 [ 0.18232156 -1.2039728 ]
 [ 0.40546511  0.78845736]]


In [37]:
matmul1 = np.matmul(logged, exponential)
matmul2 = np.matmul(exponential, logged)

print(matmul1)
print(matmul2)


[[ 1.44108036e+01  6.03529115e+10  4.39580713e+12]
 [ 1.20754286e+01 -6.42240618e+10 -4.67776415e+12]
 [ 3.03205327e+01  4.20590657e+10  3.06337283e+12]]
[[ 1.06902790e+04 -7.04197733e+04]
 [ 1.58506868e+12  2.99914875e+12]]


## Random


### Random integers


In [38]:
print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=14,
                               size=(2, 2))
print(repr(random_arr))


3
1
5
array([[ 7,  1],
       [ 3, -2]])


The np.random.randint function takes in a single required argument, which actually depends on the high keyword argument. If high=None (which is the default value), then the required argument represents the upper (exclusive) end of the range, with the lower end being 0. Specifically, if the required argument is n, then the random integer is chosen uniformly from the range [0, n).

If high is not None, then the required argument will represent the lower (inclusive) end of the range, while high represents the upper (exclusive) end.

The size keyword argument specifies the size of the output array, where each integer in the array is randomly drawn from the specified range. As a default, np.random.randint returns a single integer.




### Utility functions


In [39]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))


5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


In [40]:
vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))


array([3, 4, 2, 5, 1])
array([5, 3, 4, 2, 1])
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])


### Distributions


In [41]:
print(np.random.uniform())
print(np.random.uniform(low=-1.5, high=2.2))
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=-3.4, high=5.9,
                             size=(2, 2))))


0.3132735169322751
0.4408281904196243
array([0.44345289, 0.22957721, 0.53441391])
array([[5.09984683, 0.85200471],
       [0.60549667, 5.33388844]])


The function np.random.uniform actually has no required arguments. The keyword arguments, low and high, represent the inclusive lower end and exclusive upper end from which to draw random samples. Since they have default values of 0.0 and 1.0, respectively, the default outputs of np.random.uniform come from the range [0.0, 1.0).

The size keyword argument is the same as the one for np.random.randint, i.e. it represents the output size of the array.


In [42]:
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=-2.4, scale=4.0,
                            size=(2, 2))))


0.7252740646272712
4.772112039383628
array([[ 2.07318791, -2.17754724],
       [-0.89337346, -0.89545991]])


Like np.random.uniform, np.random.normal has no required arguments. The loc and scale keyword arguments represent the mean and standard deviation, respectively, of the normal distribution we sample from.


### Custom sampling


In [43]:
colors = ['red', 'blue', 'green']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2, 2),
                            p=[0.8, 0.19, 0.01])))



green
array(['blue', 'red'], dtype='<U5')
array([['red', 'red'],
       ['blue', 'red']], dtype='<U5')


In [44]:
random1 = np.random.randint(5)
random_arr = np.random.randint(3, high=10, size=(3, 5))


print(random1)
print(random_arr)


4
[[3 4 6 7 5]
 [7 3 8 6 4]
 [5 3 7 4 5]]


In [45]:
random_uniform = np.random.uniform(low=-2.5, high=1.5, size=5)

print(random_uniform)


[ 0.65711731 -2.08709597 -0.7084259   1.13438201 -1.32554341]


In [46]:
random_norm = np.random.normal(loc=2.0, scale=3.5, size=(10, 5))
print(random_norm)


[[-0.42081263  0.61136266 -0.40510445 -0.95821975 -0.34936146]
 [ 1.9556739  -1.91058622  2.82045494  7.80930762  4.59715456]
 [ 1.32857557 -1.10670137 -0.61505403  7.9235911   2.17782714]
 [-0.22948476  2.6682042   9.35089298  2.42055633  4.16021088]
 [ 3.05059612  0.76712554 -1.99881369  0.77730047  1.26887018]
 [ 4.05318117  4.93644195  5.25885728  2.99955564  5.09799407]
 [-0.64039279  6.38503854  3.79525437  0.95667508  3.70981351]
 [ 1.735499    5.96070286  7.31935886  9.64951392 -2.88773717]
 [-3.05439832  0.23436948  2.56012974  5.06659122  3.10472232]
 [-5.07770426  0.92828596  4.89791125  2.80533157  4.66703913]]


In [47]:
choices = ['a', 'b', 'c', 'd']
choice = np.random.choice(choices, p=[0.5, 0.1, 0.2, 0.2])

print(choice)


a


In [48]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)

print(arr)

[5 3 4 2 1]


## Indexing


In [49]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

arr = np.array([[6, 3], [0, 2]])
# Subarray
print(repr(arr[0]))


1
5
array([6, 3])


In [50]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))


array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


### Argmin and argmax


In [51]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(np.argmin(arr[0]))
print(np.argmax(arr[2]))
print(np.argmin(arr))


2
1
5


In [52]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(repr(np.argmin(arr, axis=0)))
print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))


array([2, 0, 1])
array([2, 2, 0])
array([1, 1, 1])


## Filtering


In [55]:
arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])
print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))
# Negated from the previous step
print(repr(~(arr != 1)))


array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])
array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


In [56]:
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])
print(repr(np.isnan(arr)))


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


In [57]:
print(repr(np.where([True, False, True])))

arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])
x_ind, y_ind = np.where(arr != 0)
print(repr(x_ind)) # x indices of non-zero elements
print(repr(y_ind)) # y indices of non-zero elements
print(repr(arr[x_ind, y_ind]))


(array([0, 2]),)
(array([1, 3]),)
array([0, 0, 1, 2])
array([1, 2, 0, 0])
array([ 2,  3,  1, -3])



The interesting thing about np.where is that it must be applied with exactly 1 or 3 arguments. When we use 3 arguments, the first argument is still the boolean array. However, the next two arguments represent the True replacement values and the False replacement values, respectively. The output of the function now becomes an array with the same shape as the first argument.


In [58]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
negatives = np.array([[-2, -5], [-1, -8]])
print(repr(np.where(np_filter, positives, negatives)))

np_filter = positives > 2
print(repr(np.where(np_filter, positives, negatives)))

np_filter = negatives > 0
print(repr(np.where(np_filter, positives, negatives)))


array([[ 1, -5],
       [-1,  4]])
array([[-2, -5],
       [ 3,  4]])
array([[-2, -5],
       [-1, -8]])


In [59]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
print(repr(np.where(np_filter, positives, -1)))


array([[ 1, -1],
       [-1,  4]])


In [60]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
print(repr(arr > 0))
print(np.any(arr > 0))
print(np.all(arr > 0))


array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
True
False


In [61]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
print(repr(arr > 0))
print(repr(np.any(arr > 0, axis=0)))
print(repr(np.any(arr > 0, axis=1)))
print(repr(np.all(arr > 0, axis=1)))


array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
array([ True,  True,  True])
array([False,  True,  True])
array([False, False,  True])


The np.any function is equivalent to performing a logical OR (||), while the np.all function is equivalent to a logical AND (&&) on the first argument. np.any returns true if even one of the elements in the array meets the condition and np.all returns true only if all the elements meet the condition. When only a single argument is passed in, the function is applied across the entire input array, so the returned value is a single boolean.

However, if we use a multi-dimensional input and specify the axis keyword argument, the returned value will be an array. The axis argument has the same meaning as it did for np.argmin and np.argmax from the previous chapter. Using axis=0 means the function finds the index of the minimum row element for each column. When we used axis=1, the function finds the index of the minimum column element for each row.

Setting axis to -1 just means we apply the function across the last dimension.


In [62]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
has_positive = np.any(arr > 0, axis=1)
print(has_positive)
print(repr(arr[np.where(has_positive)]))


[False  True  True]
array([[ 4,  5, -6],
       [ 3,  9,  1]])


## Statistics 


In [63]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr.min())
print(arr.max())

print(repr(arr.min(axis=0)))
print(repr(arr.max(axis=-1)))


-60
72
array([ -3,  -2, -60])
array([72,  3,  4])


In [67]:
print(repr(arr.min(axis=0)))


array([ -3,  -2, -60])


In [68]:
print(repr(arr.min(axis=1)))


array([  0, -60,  -3])


The axis keyword argument is identical to how it was used in np.argmin and np.argmax from the chapter on Indexing. In our example, we use axis=0 to find an array of the minimum values in each column of arr and axis=1 to find an array of the maximum values in each row of arr.


In [70]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(np.mean(arr))
print(np.var(arr))
print(np.median(arr))
print(np.median(arr, axis=0))
print(np.median(arr, axis=1))
print(np.median(arr, axis=-1))
print(repr(np.median(arr, axis=-1)))


2.0
977.3333333333334
1.0
[0. 3. 3.]
[ 3.  1. -2.]
[ 3.  1. -2.]
array([ 3.,  1., -2.])


## Aggregation


In [71]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(np.sum(arr))
print(repr(np.sum(arr, axis=0)))
print(repr(np.sum(arr, axis=1)))


18
array([ -2,  73, -53])
array([ 75, -56,  -1])


In [72]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(repr(np.cumsum(arr)))
print(repr(np.cumsum(arr, axis=0)))
print(repr(np.cumsum(arr, axis=1)))


array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])
array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])
array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])


In addition to regular sums, NumPy can perform cumulative sums using np.cumsum. Like np.sum, np.cumsum also takes in a NumPy array as a required argument and uses the axis argument. If the axis keyword argument is not specified, np.cumsum will return the cumulative sums for the flattened array.

The code below shows how to use np.cumsum. For a 2-D NumPy array, setting axis=0 returns an array with cumulative sums across each column, while axis=1 returns the array with cumulative sums across each row. Not setting axis returns a cumulative sum across all the values of the flattened array.


In [73]:
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])
print(repr(np.concatenate([arr1, arr2])))
print(repr(np.concatenate([arr1, arr2], axis=1)))
print(repr(np.concatenate([arr2, arr1], axis=1)))


array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
array([[-15,   6,   1,   0,  72,   3],
       [  8,   9,  -4,   1,   3, -60],
       [  5, -21,  18,  -3,  -2,   4]])


An important part of aggregation is combining multiple datasets. In NumPy, this equates to combining multiple arrays into one. The function we use to do this is np.concatenate.

Like the summation functions, np.concatenate uses the axis keyword argument. However, the default value for axis is 0 (i.e. dimension 0). Furthermore, the required argument for np.concatenate is a list of arrays, which the function combines into a single array.

The code below shows how to use np.concatenate, which aggregates arrays by joining them along a specific dimension. For 2-D arrays, not setting the axis argument (defaults to axis=0) concatenates the arrays vertically. When we set axis=1, the arrays are concatenated horizontally.


## Saving Data


In [74]:
arr = np.array([1, 2, 3])

# Saves to 'arr.npy'
#np.save('arr.npy', arr)

# Also saves to 'arr.npy'
#np.save('arr', arr)


In [75]:
arr = np.array([1, 2, 3])

#np.save('arr.npy', arr)
#load_arr = np.load('arr.npy')
#print(repr(load_arr))

# Will result in FileNotFoundError
#load_arr = np.load('arr')


# Data Analysis with pandas
