<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span><ul class="toc-item"><li><span><a href="#What-is-Machine-Learning?" data-toc-modified-id="What-is-Machine-Learning?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>What is Machine Learning?</a></span><ul class="toc-item"><li><span><a href="#Supervised-learning" data-toc-modified-id="Supervised-learning-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Supervised learning</a></span></li><li><span><a href="#Unsupervised-Learning" data-toc-modified-id="Unsupervised-Learning-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Unsupervised Learning</a></span></li></ul></li><li><span><a href="#ML-vs.-AI-vs.-Data-Science" data-toc-modified-id="ML-vs.-AI-vs.-Data-Science-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>ML vs. AI vs. Data Science</a></span></li><li><span><a href="#7-Steps-of-the-Machine-Learning-Process" data-toc-modified-id="7-Steps-of-the-Machine-Learning-Process-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>7 Steps of the Machine Learning Process</a></span></li></ul></li><li><span><a href="#Data-Manipulation-with-NumPy" data-toc-modified-id="Data-Manipulation-with-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Data Manipulation with NumPy</a></span><ul class="toc-item"><li><span><a href="#Arrays" data-toc-modified-id="Arrays-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Arrays</a></span></li><li><span><a href="#Basics" data-toc-modified-id="Basics-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Basics</a></span><ul class="toc-item"><li><span><a href="#arange" data-toc-modified-id="arange-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>arange</a></span></li><li><span><a href="#linspace" data-toc-modified-id="linspace-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>linspace</a></span></li><li><span><a href="#reshape" data-toc-modified-id="reshape-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>reshape</a></span></li><li><span><a href="#flatten" data-toc-modified-id="flatten-2.2.4"><span class="toc-item-num">2.2.4&nbsp;&nbsp;</span>flatten</a></span></li><li><span><a href="#Transposing" data-toc-modified-id="Transposing-2.2.5"><span class="toc-item-num">2.2.5&nbsp;&nbsp;</span>Transposing</a></span></li><li><span><a href="#Zeros-and-ones" data-toc-modified-id="Zeros-and-ones-2.2.6"><span class="toc-item-num">2.2.6&nbsp;&nbsp;</span>Zeros and ones</a></span></li></ul></li><li><span><a href="#Math" data-toc-modified-id="Math-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Math</a></span><ul class="toc-item"><li><span><a href="#Arithmetic" data-toc-modified-id="Arithmetic-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>Arithmetic</a></span></li><li><span><a href="#Non-linear-functions" data-toc-modified-id="Non-linear-functions-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>Non-linear functions</a></span></li></ul></li></ul></li></ul></div>

# Introduction


## What is Machine Learning?

Machine learning is the branch of science that deals with algorithms and systems performing specific tasks using patterns and inference, rather than explicitly programmed instructions. There are a variety of different use cases for machine learning, from image recognition to text generation. Most machine learning tasks generalize to one of the following two learning types:

### Supervised learning

Using labeled data to train a model. The labels for the training dataset represent the class/category that each data observation belongs to. After training, the model should be able to predict labels for new data observations (from the same population distribution as the training data).

Example: Let’s say you’re training a machine learning model to predict whether a picture contains a lake or not. With supervised learning, you would train a model on a dataset of pictures where the label for each picture is “Yes” if it contains a lake or “No” if it doesn’t. After training, the model will be able to take in a picture and determine whether or not it contains a lake.


### Unsupervised Learning

Using unlabeled data to allow a model to learn relationships between data observations and pick up on underlying patterns. Most data in the world is unlabeled, which makes unsupervised learning a very useful method of machine learning.

Example: Going back to the same picture dataset from above, but now assume the training dataset is unlabeled. Using unsupervised learning, a model will be able to pick up on the inherent differences between pictures with a lake and pictures without a lake, e.g. differences in pixel color or orientation. This allows the model to cluster the pictures into two separate groups.
If it is possible to get large enough labeled training datasets, supervised learning is the way to go. However, it is often difficult to get fully labeled datasets, which is why many tasks require unsupervised learning or semi-supervised learning (a mix of supervised and unsupervised learning). Deciding which type of learning method to use is only the first step towards creating a machine learning model. You also need to choose the proper model architecture for your task and, most importantly, be able to process data into a training pipeline and interpret/analyze model results.

## ML vs. AI vs. Data Science

People often throw around the terms “machine learning”, “artificial intelligence”, and “data science” interchangeably. In reality, machine learning is a subset of artificial intelligence and overlaps heavily with data science. Artificial intelligence deals with any technique that allows machines to display “intelligence”, similar to humans. Machine learning is one of the main techniques used to create artificial intelligence, but other non-ML techniques (e.g. alpha-beta pruning, rule-based systems) are also widely used in AI.

On the other hand, data science deals with gathering insights from datasets. Traditionally, data scientists have used statistical methods for gathering these insights. However, as machine learning continues to grow, it has also penetrated into the field of data science.

In industry, any data scientist or AI researcher needs to have a good understanding of machine learning. Machine learning in industry has allowed us to create wonderful autonomous systems. These systems have matched, or sometimes even exceeded, the best human performance in their respective fields. A good example is AlphaGo, a machine-learning based system that has beaten the best human Go players in the world.

## 7 Steps of the Machine Learning Process

Data Collection: The process of extracting raw datasets for the machine learning task. This data can come from a variety of places, ranging from open-source online resources to paid crowdsourcing. The first step of the machine learning process is arguably the most important. If the data you collect is poor quality or irrelevant, then the model you train will be poor quality as well.

- Data Processing and Preparation: Once you’ve gathered the relevant data, you need to process it and make sure that it is in a usable format for training a machine learning model. This includes handling missing data, dealing with outliers, etc.

- Feature Engineering: Once you’ve collected and processed your dataset, you will likely need to transform some of the features (and sometimes even drop some features) in order to optimize how well a model can be trained on the data.

- Model Selection: Based on the dataset, you will choose which model architecture to use. This is one of the main tasks of industry engineers. Rather than attempting to come up with a completely novel model architecture, most tasks can be thoroughly performed with an existing architecture (or combination of model architectures).

- Model Training and Data Pipeline: After selecting the model architecture, you will create a data pipeline for training the model. This means creating a continuous stream of batched data observations to efficiently train the model. Since training can take a long time, you want your data pipeline to be as efficient as possible.

- Model Validation: After training the model for a sufficient amount of time, you will need to validate the model’s performance on a held-out portion of the overall dataset. This data needs to come from the same underlying distribution as the training dataset, but needs to be different data that the model has not seen before.

- Model Persistence: Finally, after training and validating the model’s performance, you need to be able to properly save the model weights and possibly push the model to production. This means setting up a process with which new users can easily use your pre-trained model to make predictions.



# Data Manipulation with NumPy


## Arrays


In [1]:
import numpy as np  # import the NumPy library

# Initializing a NumPy array
arr = np.array([-1, 2, 5], dtype=np.float32)

# Print the representation of the array
print(repr(arr))


array([-1.,  2.,  5.], dtype=float32)


In [3]:
arr = np.array([0, 1, 2])
print(arr.dtype)
print(arr)

arr = arr.astype(np.float32)
print(arr.dtype)
print(arr)



int64
[0 1 2]
float32
[0. 1. 2.]


In [4]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))
print(arr)

arr = np.array([np.nan, 'abc'])
print(repr(arr))
print(arr)

# Will result in a ValueError
np.array([np.nan, 1, 2], dtype=np.int32)


array([nan,  1.,  2.])
[nan  1.  2.]
array(['nan', 'abc'], dtype='<U32')
['nan' 'abc']


ValueError: cannot convert float NaN to integer

Infinity

To represent infinity in NumPy, we use the np.inf special value. We can also represent negative infinity with -np.inf.

The code below shows an example usage of np.inf. Note that np.inf cannot take on an integer type.


In [5]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))
print(arr)

arr = np.array([-np.inf, 1])
print(repr(arr))
print(arr)

# Will result in an OverflowError
np.array([np.inf, 3], dtype=np.int32)


True
array([inf,  5.])
[inf  5.]
array([-inf,   1.])
[-inf   1.]


OverflowError: cannot convert float infinity to integer

In [7]:
arr = np.array([np.nan, 2, 3, 4, 5])

arr2 = arr.copy()
arr2[0] = 10

print(arr[0])
print(arr2[0])


nan
10.0


In [9]:
loat_arr = np.array([1, 5.4, 3])
float_arr2 = arr2.astype(np.float32)

print(loat_arr)
print(float_arr2)


[1.  5.4 3. ]
[10.  2.  3.  4.  5.]


In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6]],
                  dtype=np.float32)

print(matrix)


[[1. 2. 3.]
 [4. 5. 6.]]


## Basics


### arange


In [12]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))



array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


### linspace


To specify the number of elements in the returned array, rather than the step size, we can use the np.linspace function.


In [13]:
arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))


array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


### reshape


In [14]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


### flatten


In [15]:
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


### Transposing


In [16]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


The function takes in a required first argument, which will be the array we want to transpose. It also has a single keyword argument called axes, which represents the new permutation of the dimensions.

The permutation is a tuple/list of integers, with the same length as the number of dimensions in the array. It tells us where to switch up the dimensions. For example, if the permutation had 3 at index 1, it means the old third dimension of the data becomes the new second dimension (since index 1 represents the second dimension).

The code below shows an example usage of the np.transpose function with the axes keyword argument. The shape property gives us the shape of an array.



In [18]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
print(arr)
transposed = np.transpose(arr, axes=(1, 2, 0))
print(transposed)

print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[ 0  8 16]
  [ 1  9 17]]

 [[ 2 10 18]
  [ 3 11 19]]

 [[ 4 12 20]
  [ 5 13 21]]

 [[ 6 14 22]
  [ 7 15 23]]]
arr shape: (3, 4, 2)
transposed shape: (4, 2, 3)


### Zeros and ones


In [19]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))



array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


If we want to create an array of 0's or 1's with the same shape as another array, we can use np.zeros_like and np.ones_like.

The code below shows example usages of np.zeros_like and np.ones_like.


In [20]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))


array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


In [21]:
arr = np.arange(12)
reshaped = np.reshape(arr, (2, 3, 2))

print(arr)
print(reshaped)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [22]:
flattened = reshaped.flatten()
transposed = np.transpose(reshaped, axes=(1, 2, 0))


print(flattened)
print(transposed)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 1  7]]

 [[ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]]]


In [23]:
zeros_arr = np.zeros(5)
ones_arr = np.ones_like(transposed)

print(zeros_arr)
print(ones_arr)


[0. 0. 0. 0. 0.]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [25]:
points = np.linspace(-3.5, 1.5, num=101)

print(points)


[-3.5  -3.45 -3.4  -3.35 -3.3  -3.25 -3.2  -3.15 -3.1  -3.05 -3.   -2.95
 -2.9  -2.85 -2.8  -2.75 -2.7  -2.65 -2.6  -2.55 -2.5  -2.45 -2.4  -2.35
 -2.3  -2.25 -2.2  -2.15 -2.1  -2.05 -2.   -1.95 -1.9  -1.85 -1.8  -1.75
 -1.7  -1.65 -1.6  -1.55 -1.5  -1.45 -1.4  -1.35 -1.3  -1.25 -1.2  -1.15
 -1.1  -1.05 -1.   -0.95 -0.9  -0.85 -0.8  -0.75 -0.7  -0.65 -0.6  -0.55
 -0.5  -0.45 -0.4  -0.35 -0.3  -0.25 -0.2  -0.15 -0.1  -0.05  0.    0.05
  0.1   0.15  0.2   0.25  0.3   0.35  0.4   0.45  0.5   0.55  0.6   0.65
  0.7   0.75  0.8   0.85  0.9   0.95  1.    1.05  1.1   1.15  1.2   1.25
  1.3   1.35  1.4   1.45  1.5 ]


## Math


### Arithmetic


In [26]:
arr = np.array([[1, 2], [3, 4]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))


array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [28]:
def f2c(temps):
    return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))


Celsius: array([  0., -20., -10., -40.])


### Non-linear functions

In [29]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))


array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])
